version: '3.9'

services:
  postgres:
    container_name: SMIT
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - postgres_SMIT:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - '5438:5432'

#  app:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile
#    depends_on:
#      - postgres
#    restart: always
#    ports:
#      - "8000:8000"

volumes:
  postgres_SMIT: